language: php
php:
  - '5.6'
  - '7.0'

env:
  global:
      - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/codecept run; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs; fi

notifications:
  email: false